version: '3.4'

services:
  # ==========================================
  # 1. Shared Database (SQL Server)
  # ==========================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fitness_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyComplexP@ssw0rd2025
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # ==========================================
  # 2. Message Broker (RabbitMQ)
  # ==========================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitness_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # ==========================================
  # 3. Workout Service
  # ==========================================
  workoutservice:
    image: amr0101/workout-service:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - RabbitMq:Host=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  # ==========================================
  # 4. Nutrition Service
  # ==========================================
  nutritionservice:
    image: amr0101/nutrition-service:latest
    ports:
      - "8082:8080"
      - "8083:8081"
    depends_on:
      - sqlserver

  # ==========================================
  # 5. Fitness Calculation Service
  # ==========================================
  fitnesscalculationservice:
    image: amr0101/fitness-calc-service:latest
    ports:
      - "8084:8080"
      - "8085:8081"
    depends_on:
      - sqlserver

  # ==========================================
  # 6. Progress Tracking Service
  # ==========================================
  progresstrackingservice:
    image: amr0101/progress-service:latest
    ports:
      - "8086:8080"
      - "8087:8081"
    depends_on:
      - sqlserver

  # ==========================================
  # 7. API Gateway
  # ==========================================
  fitnessapigateway:
    image: amr0101/gateway-service:latest
    ports:
      - "8088:8080"
      - "8089:8081"
    depends_on:
      - workoutservice
      - nutritionservice
      - authenticationservice

  # ==========================================
  # 8. Authentication Service
  # ==========================================
  authenticationservice:
    image: amr0101/auth-service:latest
    ports:
      - "8090:8080"
      - "8091:8081"
    depends_on:
      - sqlserver

  # ==========================================
  # 9. Smart Coach Service
  # ==========================================
  smartcoachservice:
    image: amr0101/smart-coach-service:latest
    ports:
      - "8094:8080"
      - "8095:8081"
    depends_on:
      - sqlserver

volumes:
  sql_data:
  rabbitmq_data:
